### ISSUE TITLE
Adding an "about" description

### ISSUE THREAD

**Issue by N4SIRODDIN3** [cslotboom/OpenSeesPyTutorials#1]
Hello,
I think adding an " about" description will ease the process of searching over Github, don't you think?
I propose a description for you as follows: A repository for OpenSEESpy.

**Comment by cslotboom** [comment]
Hey, thanks for your comment! I've added an about page. Hope the tutorials are useful.

**Comment by N4SIRODDIN3** [comment]
That one was the bomb by the way.
